### ISSUE TITLE
ssh to remote raspberry pi

### ISSUE THREAD

**Issue by radionko** [r4mos/youtube-dl-remote-server#1]
i receive this output whenever i ssh to my raspberry box, i do not know what cause it:

user@local:~$ ssh azdija
Linux azdija 3.12.28+ #709 PREEMPT Mon Sep 8 15:28:00 BST 2014 armv6l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
You have new mail.
Last login: Thu Jan 15 15:40:24 2015 from IP
user@remote~ $ 
Updated successfully

Updated successfully
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/drakone/.config/ydlss/youtube-dl-simple-server/__main__.py", line 13, in <module>
  File "/home/drakone/.config/ydlss/youtube-dl-simple-server/youtube_dl_simple_server/__init__.py", line 32, in main
    
  File "/home/drakone/.config/ydlss/youtube-dl-simple-server/youtube_dl_simple_server/__init__.py", line 84, in runServer
    
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

**Comment by r4mos** [comment]
That's a problem for youtube-dl-simple-server.

It happens because you try to use a port that is in use. Checks that does not start twice. Go to end of file "~/.profile" where there should be only one line to start the server like:

/home/r4mos/.config/ydlss/youtube-dl-simple-server &

If there were more, delete.

if not, find the process using port with netstat -punlt |grep ':49149'

**Comment by radionko** [comment]
you were right!
there were 2 lines. i deleted both - is there a way for me to run this as a
service or daemon?

**Comment by r4mos** [comment]
I don't know how the services or daemons run on linux, I've only generated an executable program. If you can do the job or know someone who knows, contributions are welcome.

Take care,
r4mos
